/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import com.mysql.cj.protocol.Resultset;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author kaazif
 */
public class returnbook extends javax.swing.JFrame {

    /**
     * Creates new form issuebook
     */
    public returnbook() {
        initComponents();
    }
    public  void issuebookdetails(){
        
        int bookid = Integer.parseInt(txtbookID.getText());
        int studentid =Integer.parseInt(txtstudentid.getText());
        try {
            Connection con = DBConnection.getConnection();
            String sql = "select * from issue_book_details where book_id =? and student_id =? and status =?";
            PreparedStatement pat = con.prepareStatement(sql);
            pat.setInt(1, bookid);
            pat.setInt(2, studentid);
            pat.setString(3, "pending");
            
            ResultSet rs = pat.executeQuery();
            if (rs.next()) {
               
                lblissue_id.setText(rs.getString("id"));
                lbl_bookName.setText(rs.getString("book_name"));
                lblstudent.setText(rs.getString("student_name"));
                lblissue.setText(rs.getString("issue_date"));
                lblduedate.setText(rs.getString("due_date"));
                lblbookerror.setText("");
                
            }else{
                
                
                lblissue_id.setText("");
                lbl_bookName.setText("");
                lblstudent.setText("");
                lblissue.setText("");
                lblduedate.setText("");
                lblbookerror.setText("");
                
                lblbookerror.setText("No Record Found");
                
                
                
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
       
    }
    public boolean returnBook(){
        boolean isReturned = false;
        int bookid = Integer.parseInt(txtbookID.getText());
        int studentid =Integer.parseInt(txtstudentid.getText());
        try {
            Connection con = DBConnection.getConnection();
            String sql = "update issue_book_details set status =? where student_id =? and book_id =? and status =?";
            PreparedStatement pat = con.prepareStatement(sql);
            pat.setString(1, "returned");
            pat.setInt(2, studentid);
            pat.setInt(3, bookid);
            pat.setString(4, "pending");
            
            int rowCount = pat.executeUpdate();
            if (rowCount >0) {
                isReturned =true;
                
            }else{
                isReturned = false;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return isReturned;
        
    }

    

 
   
    public void updateBookCOunt(){
        int bookId = Integer.parseInt(txtbookID.getText());
        try {
            Connection con = DBConnection.getConnection();
            String sql = "update book_details set quantity = quantity + 1 where book_id =?";
            PreparedStatement pat = con.prepareStatement(sql);
            pat.setInt(1, bookId);
            
            int rowCount = pat.executeUpdate();
            
             if (rowCount > 0) {
                JOptionPane.showMessageDialog(this, "Book Count Updated");
                
                
              
            }else{
                JOptionPane.showMessageDialog(this, "cant update book count");;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblissue = new javax.swing.JLabel();
        lblissue_id = new javax.swing.JLabel();
        lbl_bookName = new javax.swing.JLabel();
        lblstudent = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblbookerror = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblduedate = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtbookID = new app.bolivia.swing.JCTextField();
        txtstudentid = new app.bolivia.swing.JCTextField();
        jLabel19 = new javax.swing.JLabel();
        rSMaterialButtonCircle2 = new rojerusan.RSMaterialButtonCircle();
        lbl_quantity1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rSMaterialButtonCircle3 = new rojerusan.RSMaterialButtonCircle();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_main.setBackground(java.awt.Color.white);
        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 25)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel2.setText("Book Details");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Book Name :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Student Name  :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, 40));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Issue ID :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        lblissue.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblissue.setForeground(java.awt.Color.white);
        jPanel1.add(lblissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 190, 30));

        lblissue_id.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblissue_id.setForeground(java.awt.Color.white);
        jPanel1.add(lblissue_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 190, 30));

        lbl_bookName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lbl_bookName.setForeground(java.awt.Color.white);
        jPanel1.add(lbl_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 190, 30));

        lblstudent.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblstudent.setForeground(java.awt.Color.white);
        jPanel1.add(lblstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 190, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Due Date  :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        lblbookerror.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jPanel1.add(lblbookerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 640, 270, 30));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Issue Date  :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        lblduedate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblduedate.setForeground(java.awt.Color.white);
        jPanel1.add(lblduedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 190, 30));

        panel_main.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 390, 810));

        jLabel12.setBackground(java.awt.Color.white);
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 25)); // NOI18N
        jLabel12.setForeground(java.awt.Color.red);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel12.setText("Return Book");
        panel_main.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 140, -1, 50));

        jPanel7.setBackground(java.awt.Color.black);
        jPanel7.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panel_main.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 220, -1, -1));

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 51, 51));
        jLabel17.setText("Book ID :");
        panel_main.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 300, -1, -1));

        txtbookID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 51)));
        txtbookID.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtbookID.setPlaceholder("Enter Book ID..............");
        txtbookID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbookIDKeyReleased(evt);
            }
        });
        panel_main.add(txtbookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 280, 310, 40));

        txtstudentid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 51)));
        txtstudentid.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtstudentid.setPlaceholder("Enter Student Id..............");
        txtstudentid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtstudentidKeyReleased(evt);
            }
        });
        panel_main.add(txtstudentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 360, 310, 40));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 51, 51));
        jLabel19.setText("Student ID :");
        panel_main.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 380, -1, -1));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(255, 51, 51));
        rSMaterialButtonCircle2.setText("Return Book");
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        panel_main.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 580, 360, 70));

        lbl_quantity1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lbl_quantity1.setForeground(java.awt.Color.white);
        panel_main.add(lbl_quantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 190, 30));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel1.setText(" back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_main.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 50));

        rSMaterialButtonCircle3.setBackground(new java.awt.Color(102, 102, 255));
        rSMaterialButtonCircle3.setText("Find");
        rSMaterialButtonCircle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle3ActionPerformed(evt);
            }
        });
        panel_main.add(rSMaterialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 480, 360, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/library-2.png"))); // NOI18N
        panel_main.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 50, 910, 650));

        getContentPane().add(panel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        // TODO add your handling code here:
        if (returnBook() == true) {
            JOptionPane.showMessageDialog(this, "Book Returned Successfully");
            updateBookCOunt();
            
        }else{
            JOptionPane.showMessageDialog(this, "Book Returned failed");
            
        }
        
        
        
        
        

    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void txtbookIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbookIDKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtbookIDKeyReleased

    private void txtstudentidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstudentidKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtstudentidKeyReleased

    private void rSMaterialButtonCircle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3ActionPerformed
        // TODO add your handling code here:
        issuebookdetails();
    }//GEN-LAST:event_rSMaterialButtonCircle3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new returnbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbl_bookName;
    private javax.swing.JLabel lbl_quantity1;
    private javax.swing.JLabel lblbookerror;
    private javax.swing.JLabel lblduedate;
    private javax.swing.JLabel lblissue;
    private javax.swing.JLabel lblissue_id;
    private javax.swing.JLabel lblstudent;
    private javax.swing.JPanel panel_main;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle3;
    private app.bolivia.swing.JCTextField txtbookID;
    private app.bolivia.swing.JCTextField txtstudentid;
    // End of variables declaration//GEN-END:variables
}
